### ISSUE TITLE
Message Corruption with multiple secondary instances

### ISSUE THREAD

**Issue by larisb** [itay-grudev/SingleApplication#75] opened 2019-10-11 02:37 UTC
Thanks for SingleApplication!
However, I had a problem with my particular use case.  I have program myApplication which uses SingleApplication.  I also have an otherApplication which calls many instances of myApplication in quick succession.  The default interval for invocation is 500ms.  At 2000ms everything works fine.  At the default rate, however, the messages received by the primary will be lost, corrupted or mangled beyond recognition.

My solution to this was to add a bool parameter WAIT to shared memory.  When a secondary instance sends a message it first acquires a QSystemSemaphore and sets WAIT true.  It sends the message and then waits for WAIT to become false.  When the primary is ready to receive another secondary message it emits a signal which connects to primary::slotReadyforNewInstance which sets WAIT false.  The secondary then releases the semaphore allowing another secondary to send a message.

Only tested on windows and have not looked at corner cases of primary or secondary crashes

[singleapplication.cpp.diff.txt](https://github.com/itay-grudev/SingleApplication/files/3715386/singleapplication.cpp.diff.txt)
[singleapplication.h.diff.txt](https://github.com/itay-grudev/SingleApplication/files/3715387/singleapplication.h.diff.txt)
[singleapplication_p.cpp.diff.txt](https://github.com/itay-grudev/SingleApplication/files/3715388/singleapplication_p.cpp.diff.txt)
[singleapplication_p.h.diff.txt](https://github.com/itay-grudev/SingleApplication/files/3715389/singleapplication_p.h.diff.txt)

Hope you find this useful

Laris

**Comment by itay-grudev** [comment] 2019-10-11 06:55
That makes no sense, because this is a standard client-server architecture. The client opens a separate socket and unless there is some weird Qt bug date from one socket should not go into the other.

**Comment by larisb** [comment] 2019-10-11 11:30
I was assuming the messages were overflowing a queue on the server which, I admit, sounds unlikely.  Anyway it’s working for me now.  Thanks.

Laris

**Comment by itay-grudev** [comment] 2019-10-11 13:25
I will close this for now. If anyone else encounters this issue I will reopen it, but please do provide some code that reproduces the issue.

**Closed by itay-grudev** 2019-10-11 13:25 UTC
